# Generated by Django 3.1.2 on 2023-02-03 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='designation',
            field=models.CharField(choices=[('Professor', 'Professor'), ('Asst Professor', 'Asst Professor'), ('Associate professor', 'Associate professor')], max_length=20),
        ),
    ]
